image: maven:latest
osx_image: xcode9.3
sudo: false

# NOTE: `shell` is compatible with Windows os which doesn't support `language: java`
language: shell

os:
  - linux
  - osx
  - windows

branches:
  only:
    - master

# Install OpenJDK 8 and Maven on Linux (Ubuntu - Xenial)
addons:
  apt:
    packages:
      - openjdk-8-jdk
      - maven

# Install OpenJDK 8 (Zulu) and Maven on Windows
before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == windows ]; then
      choco install -y zulu8
      choco install -y maven --version 3.8.1
      export PATH=/C/Program\ Files/Zulu/zulu-8/bin:/C/ProgramData/chocolatey/lib/maven/apache-maven-3.8.1/bin:$PATH
      echo "PATH=${PATH}"
    fi

install: /usr/bin/env true

script: mvn clean install site -DperformRelease=true -Dgpg.skip=true -V -B -s settings.xml -Dmaven.artifact.threads=64 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

cache:
  #  timeout: 5000
  directories:
    - "$HOME/.m2"
    - $HOME/AppData/Local/Temp/chocolatey
    - $HOME/Library/Caches/Homebrew
