osx_image: xcode9.3
sudo: false

# NOTE: `shell` is compatible with Windows os which doesn't support `language: java`
language: shell

os:
  - linux
  - osx
  - windows

branches:
  only:
    - master

# Install OpenJDK 8 and Maven on Linux (Ubuntu - Xenial)
addons:
  apt:
    packages:
      - openjdk-8-jdk
      - maven

# Install OpenJDK 8 (Zulu) and Maven on Windows
before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == windows ]; then
      choco install -y zulu8
      choco install -y maven
      export PATH=/C/Program\ Files/Zulu/zulu-8/bin:/C/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin:$PATH
      echo "PATH=${PATH}"
    fi

install: /usr/bin/env true

script: mvn clean install --quiet -B -Dmaven.artifact.threads=64 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

before_cache:
  - |
    find $HOME/.m2/repository/ -name *SNAPSHOT | xargs rm -Rf
    if [ "${TRAVIS_OS_NAME}" == osx ]; then
      brew cleanup
    fi

cache:
  timeout: 1000
  directories:
    - "$HOME/.m2"
    - $HOME/AppData/Local/Temp/chocolatey
    - $HOME/Library/Caches/Homebrew
